baseURL = "http://prtamil.github.io/"
languageCode = "en-us"
title = "Carpe diem"
author = "Tamilselvan P.R"
#theme = "devise"
theme =  "hugo-vitae"
paginate = 10

#Chroma syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
copyright = "&copy; 2020, Tamilselvan Rangasami"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
    description = "Tamilselvans Experience on Programming"
    pagetitle = "All about Programming and Computer Science"
    subtitle = "Tamilselvan is a Peaceful Programmer. "
    avatar = "/images/tamil1.jpg"
#header_title = "Carpe diem"
#header_subtitle = "Tamilselvans Blog about Programming"
#home_image = "/images/tamil1.jpg"
#recent_posts = 10
#mainSections = ["posts", "post", "blog"]

    [[params.social]]
        icon = "fab fa-github"
        title = "Github"
        url = "https://github.com/prtamil"
    [[params.social]]
        icon = "fab fa-linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/tamil-selvan-ab46927/"
    [[params.social]]
        icon = "fab fa-facebook"
        title = "Facebook"
        url = "https://www.facebook.com/prtamil"
    [[params.social]]
        icon = "fab fa-twitter"
        title = "Twitter"
        url = "https://twitter.com/prtamil"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"

